### ISSUE TITLE
Package versions, missing packages, and dependencies

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/gEAR#1]
There are many pinned (older) versions of python packages, and dependencies will eventually be a problem...
The gEAR developers have already started to work on this, see below.

Minor changes are only documented in [CHANGELOG](https://github.com/dieterich-lab/gEAR/blob/DHART/CHANGELOG.md).
See also Ansible install playbook. 
We should eventually move to testing.

---

Regarding the `diffxpy` install, we need to make sure it is installed in the virtual environment as `www-data` user. 
We can make a test install using 

```
pip install pip-install-test
pip show pip_install_test
python -c 'import pip_install_test'
```
then

```
pip install git+https://github.com/adkinsrs/diffxpy.git@b2ebeb0fb7c6c215d51264cd258edf9d013ff021
```

But we should find a better solution in the long term.

We also found out that we had issues with dash (probably due to the force re-install), see
[ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools](https://github.com/plotly/dash/issues/1992)
We could try `pip install Werkzeug==2.0.0` in the virtual environment, or solve the dependency problem if possible.
Now we are left with

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dash-bio 0.6.1 requires dash>=1.6.1, but you have dash 1.3.0 which is incompatible.
```

We also found out that `ModuleNotFoundError: No module named 'rpy2'`.
This is used in `www/api/resources/projectr.py`, and 

```
line 30 from resources.projectr import ProjectR
line 42 api.add_resource(ProjectR, '/projectr/<dataset_id>')
```

in `www/api/api.py`.

But this is not mentioned anywhere except in `docker/requirements.txt`? And the install won't be successful unless
we have a running `R` installation... so how is this working?

See [Implement ProjectR](https://github.com/IGS/gEAR/issues/243)

---

There is a _software_update_bugfixes_ branch on gEAR, apparently started on https://github.com/IGS/gEAR/commit/cc89c46769ce35bd581e48534ae4ce343347970c, with following updated dependencies

```
anndata==0.8.0 \
biocode==0.10.0 \
biopython==1.79 \
dash-bio==1.0.2 \
Flask==2.1.0 \
Flask-RESTful==0.3.9 \
h5py==3.6.0 \
itsdangerous==2.1.2 \
jupyter==1.0.0 \
kaleido==0.2.1 \
llvmlite==0.38.0 \
mod-wsgi==4.9.0 \
MulticoreTSNE==0.1 \
mysql-connector-python==8.0.28 \
numba==0.55.1 \
numexpr==2.8.1 \
numpy==1.21.5 \
opencv-python==4.5.5.64 \
pandas==1.4.1 \
Pillow==9.0.1 \
plotly==5.6.0 \
python-dotenv==0.20.0 \
requests==2.27.1 \
scanpy==1.8.2 \
scanpy[louvain]==1.8.2 \
scikit-learn==1.0.2 \
scipy==1.8.0 \
SQLAlchemy==1.4.32 \
xlrd==2.0.1
```

but it is not yet integrated. See also [Commits software_update_bugfixes](https://github.com/IGS/gEAR/commits/software_update_bugfixes), and also [Backup production and update OS and all libraries on devel](https://github.com/IGS/gEAR/issues/299). 

It seems as if some earlier changes _e.g._ commit  `ae11f63449d7bda768bf6f9503aa3ec2ff42cda7` on `www/api/resources/multigene_dash_data.py` are lost...

It is not easy to find associated commits that would resolve issues associated with upgrade...

**Comment by eboileau** [comment]
Thanks for your feedback @adkinsrs

We are working on setting-up our own server, called DHART (Digital HeART), which will have a focus on heart data.
The gEAR framework is great, but admittedly it takes a bit of time to understand everything, at least for me, it was
the first time setting-up a LAMP stack. 

I've already set-up a dev server locally, starting from gEAR, and automated the installation using **Ansible**. 
I will make that available in the coming days, in case your interested. 
I wasn't sure of the status of the _software_update_bugfixes_ branch on gEAR, so I decided to start working from _main_, but upgraded Python, _etc._ So I'm fixing a few things, and will move to customize appearance next.

I don't know how easy it will be to PR as I move along, but in any case, I'd be happy to share my progress, discuss any improvements... and keep in touch!

**Comment by adkinsrs** [comment]
I will loop in @jorvis and @jpreceveur in case they have anything extra to add, or at the least let them know of your efforts.

I believe working from "main" is definitely the right call, though the "software_update_bugfixes" branch does have a few commits on documentation.  We were originally going to fix potential issues related to updating our software base in that branch, but there were minimal changes that needed to be made (outside of one I am working on right now).  

If you are looking to re-skin the portal for DHART, feel free to check out https://github.com/IGS/gEAR/tree/main/www/css/by_domain where @jorvis has done a few other "flavors" of the gEAR portal already.  However do note that the "purple" colorscheme is still hardcoded in a few of the other CSS files, and I hope to eventually get around to resolving that.

**Comment by eboileau** [comment]
@adkinsrs Thanks for your feedback. In case you're interested, here is the Ansible install https://github.com/eboileau/gear_lamp.

**Comment by eboileau** [comment]
So far so good. DHART has a slightly different setup than gEAR, but no major issues. For our own install, we use the [DHART Ansible install](https://github.com/eboileau/gear_lamp).
