### ISSUE TITLE
No profile (layout) fails on dataset explorer

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/gEAR#4]
```
Traceback (most recent call last):
  File "/var/www/cgi/get_users_layout_members.cgi", line 36, in <module>
    main()
  File "/var/www/cgi/get_users_layout_members.cgi", line 28, in main
    if layout.user_id == user.id:
AttributeError: 'NoneType' object has no attribute 'user_id'
```

`geardb.get_layout_by_id` returns `None` if no layout is found, hence in `get_users_layout_members.cgi` there should be a check before evaluating `if layout.user_id == user.id`. 

What other consequences does this have if a user has no profile?

See [New portal with no profiles fails on dataset explorer page](https://github.com/IGS/gEAR/issues/3)

**Comment by adkinsrs** [comment]
pushed a small commit on IGS/gEAR to address this.

https://github.com/IGS/gEAR/commit/7364a9efd4b905578d4d2f21208698cc89110ece
